const { test } = require('node:test');
const assert = require('node:assert/strict');
const { mkdtempSync, rmSync } = require('node:fs');
const { tmpdir } = require('node:os');
const { join } = require('node:path');
const { once } = require('node:events');
const { createHash } = require('node:crypto');
const { DatabaseSync } = require('node:sqlite');
const { createService, createMemoryRepository } = require('../src/returns/service.js');
const { createSqliteRepository } = require('../server/returns-repository.cjs');
const { createService: notifications } = require('../src/notifications/service.js');
const { createHttpClient, createLocalClient } = require('../src/notifications/client.js');
const { createApiServer, tokenAuthenticator } = require('../server/returns-api.cjs');
const { sample } = require('./returns-fixtures.cjs');
const clock = () => '2026-09-08T08:00:00.000Z';
const store = { shopId: 'shop-1', actor: { id: 'counter-1', role: 'store' } };
const second = { ...store, actor: { id: 'counter-2', role: 'store' } };
const driver = { shopId: 'shop-1', actor: { id: 'driver-1', role: 'driver', vehicleId: 'van-1' } };
const driver2 = { shopId: 'shop-1', actor: { id: 'driver-2', role: 'driver', vehicleId: 'van-2' } };
function fixture(repo = createMemoryRepository()) {
  const returns = createService(repo, store, clock), van = createService(repo, driver, clock);
  let seq = 0;
  const execute = (type, payload, client = returns, orderId = 'order-1') => client.execute({ type, payload, orderId, expectedVersion: repo.get('shop-1', orderId)?.version || 0, requestId: 'movement-' + ++seq });
  execute('create', sample()); execute('issue', { items: sample().items.map(item => ({ itemId: item.id, quantity: 2 })) });
  const pos = notifications(repo, store, clock), car = notifications(repo, driver, clock);
  return { repo, returns, van, execute, pos, car, command: (type, payload = {}, notificationId) => ({ type, payload, requestId: 'request-' + ++seq, ...(notificationId ? { notificationId } : {}) }) };
}
test('collection notifications preserve quantities, read separately and share the first acknowledgement', () => {
  const f = fixture();
  const result = f.execute('collect', { items: [{ itemId: 'ski', quantity: 1 }] }, f.van);
  const row = f.pos.list({ filter: 'unread' }).records.find(row => row.type === 'collection');
  assert.match(row.summary, /스키 1/); assert.match(row.summary, /고객에게 남음/);
  assert.equal(row.collectionId, result.requestId);
  const before = f.repo.get('shop-1', 'order-1');
  f.pos.execute(f.command('received', {}, row.id));
  assert.equal(f.pos.list({ filter: 'unread' }).unreadCount, 1);
  const command = f.command('ack', {}, row.id);
  f.pos.execute(command); assert.equal(f.pos.execute(command).duplicate, true);
  notifications(f.repo, second, clock).execute(f.command('ack', {}, row.id));
  assert.equal(f.pos.list().records[0].acknowledgedBy, 'counter-1');
  assert.deepEqual(f.repo.get('shop-1', 'order-1'), before);
  assert.equal(f.pos.list().unreadCount, 0);
});
test('requests are scoped, deduplicated and reported as received before a human acknowledgement', () => {
  const f = fixture(), command = f.command('request', { orderId: 'order-1', expectedVersion: 2, message: '고객님을 먼저 확인해 주세요.' });
  const first = f.pos.execute(command);
  assert.equal(f.pos.execute({ ...command, requestId: 'repeat' }).notificationId, first.notificationId);
  assert.equal(f.pos.sent().records[0].receivedAt, null);
  f.car.execute(f.command('received', {}, first.notificationId));
  assert.ok(f.pos.sent().records[0].receivedAt); assert.equal(f.pos.sent().records[0].acknowledgedAt, null);
  f.car.execute(f.command('ack', {}, first.notificationId));
  assert.ok(f.pos.sent().records[0].acknowledgedAt);
  assert.equal(f.pos.list().unreadCount, 0);
  assert.throws(() => f.pos.execute({ ...command, payload: { ...command.payload, message: '다른 내용' } }), { code: 'IDEMPOTENCY_CONFLICT' });
  assert.throws(() => notifications(f.repo, driver2, clock).execute(f.command('ack', {}, first.notificationId)), { code: 'NOT_FOUND' });
  assert.equal(notifications(f.repo, { ...store, shopId: 'shop-2' }, clock).list().records.length, 0);
});
test('driver help reaches the store without exposing billing data and rejects forged fields', () => {
  const f = fixture();
  f.car.execute(f.command('request', { orderId: 'order-1', expectedVersion: 2, message: '수량 확인이 필요해요' }));
  const row = f.pos.list().records[0]; assert.equal(row.type, 'help'); assert.match(row.title, /기사님 요청/);
  const vehicle = JSON.stringify(f.car.list());
  assert.ok(!vehicle.includes('amountWon')); assert.ok(!vehicle.includes('recoveryValueWon'));
  assert.throws(() => f.car.execute({ ...f.command('request', { orderId: 'order-1', expectedVersion: 2, message: '요청' }), actor: { role: 'store' } }), { code: 'INVALID_INPUT' });
  assert.throws(() => f.pos.execute(f.command('request', { orderId: 'order-1', expectedVersion: 1, message: '요청' })), { code: 'VERSION_CONFLICT' });
});
test('zero collections and corrections never report false completion or revive stale unread notices', () => {
  const f = fixture();
  const zero = f.execute('collect', { items: [{ itemId: 'ski', quantity: 0 }] }, f.van);
  assert.match(f.pos.list().records[0].title, /수거하지 못/);
  const movement = f.execute('collect', { items: [{ itemId: 'ski', quantity: 1 }] }, f.van);
  f.execute('undoReturn', { movementId: movement.requestId }, f.van);
  assert.equal(f.pos.list().records.find(row => row.collectionId === movement.requestId && row.type === 'collection').lifecycle, 'cancelled');
  assert.ok(f.pos.list({ filter: 'unread' }).records.some(row => row.type === 'correction'));
  assert.ok(zero.requestId);
});
test('new schedules supersede requests and reassignment removes old customer details', () => {
  const f = fixture();
  f.pos.execute(f.command('request', { orderId: 'order-1', expectedVersion: 2, message: '확인해 주세요' }));
  const before = f.car.sync(0).cursor;
  f.execute('planReturn', { items: [{ itemId: 'ski', returnPlan: { time: '18:00' } }] });
  const changed = f.car.sync(before);
  assert.ok(changed.records.some(row => row.type === 'priority' && row.lifecycle === 'superseded'));
  assert.ok(changed.records.some(row => row.type === 'schedule' && row.summary.includes('18:00')));
  f.execute('assignVehicle', { vehicleId: 'van-2' });
  assert.ok(f.car.list().records.filter(row => row.type !== 'cancelled').every(row => row.lifecycle === 'cancelled'));
  assert.equal(f.car.list({ filter: 'unread' }).records.length, 1);
  assert.equal(f.car.list({ filter: 'unread' }).records[0].type, 'cancelled');
  assert.ok(f.car.list().records.every(row => !row.title.includes(sample().customer.name)));
  assert.equal(notifications(f.repo, driver2, clock).list({ filter: 'unread' }).unreadCount, 1);
  assert.throws(() => f.car.execute(f.command('request', { orderId: 'order-1', expectedVersion: 4, message: '요청' })), { code: 'NOT_FOUND' });
});
test('vehicle custody prevents reassignment and final handover resolves only its collection', () => {
  const f = fixture(), first = f.execute('collect', { items: [{ itemId: 'ski', quantity: 1 }] }, f.van);
  const next = f.execute('collect', { items: [{ itemId: 'ski', quantity: 1 }] }, f.van);
  assert.throws(() => f.execute('assignVehicle', { vehicleId: 'van-2' }), { code: 'DEPENDENT_RETURN' });
  f.execute('confirmVehicle', { collectionId: first.requestId, items: [{ itemId: 'ski', quantity: 1 }] });
  const rows = f.pos.list().records;
  assert.equal(rows.find(row => row.collectionId === first.requestId).lifecycle, 'resolved');
  assert.equal(rows.find(row => row.collectionId === next.requestId).lifecycle, 'active');
});
test('persistent task IDs, updates and cancellation produce notifications from saved task data', () => {
  const f = fixture(), payload = { id: 'task-delivery-1', orderId: 'order-1', expectedVersion: 0, kind: 'delivery', vehicleId: 'van-1', date: '2026-09-08', time: '16:40', place: '설천 주차장', status: 'waiting' };
  f.pos.execute(f.command('task', payload));
  f.pos.execute(f.command('task', { ...payload, expectedVersion: 1, time: '17:00' }));
  assert.equal(f.pos.tasks()[0].id, payload.id); assert.equal(f.pos.tasks()[0].version, 2);
  f.pos.execute(f.command('task', { ...payload, expectedVersion: 2, status: 'cancelled' }));
  assert.equal(f.car.list({ filter: 'unread' }).records.filter(row => row.taskId === payload.id).length, 1);
  assert.equal(f.car.list({ filter: 'unread' }).records.find(row => row.taskId === payload.id).type, 'cancelled');
  assert.throws(() => f.car.execute(f.command('task', payload)), { code: 'FORBIDDEN' });
});
test('sound preferences are scoped to the authenticated user and reject invalid values', () => {
  const f = fixture();
  assert.equal(f.pos.preferences().sound, false);
  assert.equal(f.car.preferences().sound, true, 'vehicle notifications are enabled by default');
  f.pos.execute(f.command('preferences', { sound: true, interval: 60, volume: 30 }));
  assert.equal(f.pos.preferences().volume, 30); assert.equal(f.car.preferences().volume, 60);
  f.car.execute(f.command('preferences', { sound: false, interval: 30, volume: 60 }));
  assert.equal(f.car.preferences().sound, false, 'saved user preferences still take precedence over defaults');
  assert.throws(() => f.pos.execute(f.command('preferences', { sound: true, interval: 1, volume: 120 })), { code: 'INVALID_INPUT' });
  const a = notifications(f.repo, { ...store, deviceId: 'pos-a' }, clock);
  const b = notifications(f.repo, { ...store, deviceId: 'pos-b' }, clock);
  a.execute(f.command('preferences', { sound: true, interval: 30, volume: 80 }));
  assert.equal(a.preferences().volume, 80); assert.equal(b.preferences().sound, false);
});
test('stopping a client watcher ignores an already in-flight response', async () => {
  let resolve, changes = 0, statuses = 0;
  const client = createLocalClient({ sync: () => new Promise(done => { resolve = done; }) });
  const stop = client.watch({ onChange: () => changes++, onStatus: () => statuses++ });
  stop(); resolve({ cursor: 1, records: [], reset: true });
  await new Promise(done => setImmediate(done));
  assert.equal(changes, 0); assert.equal(statuses, 0);
});
test('SQLite keeps acknowledgements across restart and rolls back the whole collection when notification storage fails', t => {
  const folder = mkdtempSync(join(tmpdir(), 'ski-notices-')), file = join(folder, 'test.sqlite');
  t.after(() => rmSync(folder, { recursive: true, force: true }));
  let repository = createSqliteRepository(file);
  const f = fixture(repository);
  const a = f.execute('collect', { items: [{ itemId: 'ski', quantity: 1 }] }, f.van);
  const notification = f.pos.list().records.find(row => row.collectionId === a.requestId);
  f.pos.execute(f.command('ack', {}, notification.id)); repository.close();
  repository = createSqliteRepository(file);
  assert.ok(notifications(repository, store).list().records.find(row => row.id === notification.id).acknowledgedAt);
  const db = new DatabaseSync(file);
  db.exec("CREATE TRIGGER fail_notice BEFORE UPDATE ON notification_state BEGIN SELECT RAISE(ABORT, 'simulated storage failure'); END;");
  const before = repository.get('shop-1', 'order-1'), rev = repository.changes('shop-1', 0).revision;
  assert.throws(() => createService(repository, driver, clock).execute({ type: 'collect', orderId: 'order-1', expectedVersion: before.version, requestId: 'fail-transaction', payload: { items: [{ itemId: 'ski', quantity: 1 }] } }));
  assert.deepEqual(repository.get('shop-1', 'order-1'), before);
  assert.equal(repository.changes('shop-1', 0).revision, rev);
  db.close(); repository.close();
});
test('version 1 migration preserves the existing return ledger', t => {
  const folder = mkdtempSync(join(tmpdir(), 'ski-migrate-')), file = join(folder, 'test.sqlite');
  t.after(() => rmSync(folder, { recursive: true, force: true }));
  let repository = createSqliteRepository(file); fixture(repository); const before = repository.get('shop-1', 'order-1'); repository.close();
  const db = new DatabaseSync(file); db.exec('DROP TABLE notification_state; PRAGMA user_version = 1;'); db.close();
  repository = createSqliteRepository(file); assert.deepEqual(repository.get('shop-1', 'order-1'), before);
  assert.equal(notifications(repository, store).list().records.length, 0); repository.close();
});
test('two authenticated HTTP clients exchange requests and acknowledgement changes', async t => {
  const repository = createSqliteRepository(':memory:'); fixture(repository);
  const tokens = { store: 'test-notice-store-'.padEnd(40, 's'), driver: 'test-notice-driver-'.padEnd(40, 'd') };
  const contexts = { store, driver };
  const server = createApiServer({ repository, authenticate: tokenAuthenticator(Object.entries(tokens).map(([role, token]) => ({ ...contexts[role], tokenHash: createHash('sha256').update(token).digest('hex') }))), clock });
  server.listen(0, '127.0.0.1'); await once(server, 'listening');
  t.after(async () => { await new Promise(resolve => server.close(resolve)); repository.close(); });
  const baseUrl = 'http://127.0.0.1:' + server.address().port;
  const pos = createHttpClient({ baseUrl, token: tokens.store }), car = createHttpClient({ baseUrl, token: tokens.driver });
  const before = (await car.sync(0)).cursor;
  const result = await pos.execute({ type: 'request', requestId: 'http-notice', payload: { orderId: 'order-1', expectedVersion: 2, message: '먼저 확인 부탁드려요' } });
  assert.ok((await car.sync(before)).records.some(row => row.id === result.notificationId));
  await car.execute({ type: 'ack', requestId: 'http-ack', notificationId: result.notificationId, payload: {} });
  assert.ok((await pos.sent()).records[0].acknowledgedAt);
  assert.equal((await fetch(baseUrl + '/api/notifications')).status, 401);
  assert.throws(() => createHttpClient({ baseUrl: 'https://user:password@example.com', token: tokens.store }));
});
