const { test } = require('node:test');
const assert = require('node:assert/strict');
const { once } = require('node:events');
const { createHash } = require('node:crypto');
const { createApiServer, tokenAuthenticator } = require('../server/returns-api.cjs');
const { createSqliteRepository } = require('../server/returns-repository.cjs');
const { createHttpClient, createGuestHttpClient, newCommand, newIntakeCommand } = require('../src/workflows/client.js');
const { customer, ticket, person, errorCode } = require('./workflows-fixtures.cjs');

test('HTTP store/driver/guest clients share durable workflows with authorization, idempotency and public field boundaries', async t => {
  const repository = createSqliteRepository(':memory:');
  const tokens = { store: 'store-'.padEnd(40, 's'), driver: 'driver-'.padEnd(40, 'd'), other: 'other-'.padEnd(40, 'o') };
  const credentials = Object.entries(tokens).map(([name, token]) => ({ tokenHash: createHash('sha256').update(token).digest('hex'), shopId: name === 'other' ? 'shop-2' : 'shop-1', actor: { id: name, role: name === 'driver' ? 'driver' : 'store', ...(name === 'driver' ? { vehicleId: 'van-1' } : {}) } }));
  const server = createApiServer({ repository, authenticate: tokenAuthenticator(credentials), clock: () => '2026-09-09T00:00:00.000Z' });
  server.listen(0, '127.0.0.1'); await once(server, 'listening');
  t.after(async () => { await new Promise(resolve => server.close(resolve)); repository.close(); });
  const baseUrl = 'http://127.0.0.1:' + server.address().port;
  const store = createHttpClient({ baseUrl, token: tokens.store }), driver = createHttpClient({ baseUrl, token: tokens.driver }), other = createHttpClient({ baseUrl, token: tokens.other });
  await store.execute(newCommand('ticket.issue', 0, { sku: 'ticket-6h', quantity: 2, ticket }));
  const preview = await store.prepareMove({ kind: 'load', from: { kind: 'shop', id: 'shop-1' }, to: { kind: 'vehicle', id: 'van-1' }, items: [{ sku: 'ticket-6h', quantity: 2 }] });
  const command = newCommand('stock.move', preview.revision, preview.payload);
  const [first, duplicate] = await Promise.all([store.execute(command), store.execute(command)]);
  assert.equal(Number(first.duplicate) + Number(duplicate.duplicate), 1);
  assert.equal((await driver.vehicle()).totals.at(-1).current, 2);
  assert.equal((await other.snapshot()).assets.length, 0);
  await assert.rejects(driver.execute(newCommand('stock.receive', await store.snapshot(), { sku: 'ski', quantity: 1 })), errorCode('FORBIDDEN'));
  await assert.rejects(driver.reservations(), errorCode('FORBIDDEN'));
  await assert.rejects(store.execute({ ...command, actor: { role: 'store' } }), errorCode('INVALID_INPUT'));
  await assert.rejects(store.execute({ ...command, requestId: 'stale' }), errorCode('VERSION_CONFLICT'));
  const form = await newIntakeCommand(await store.snapshot(), { id: 'form-1', customer, expectedPeople: 1, expiresAt: '2026-09-11T00:00:00.000Z' });
  await store.execute(form.command);
  const guest = createGuestHttpClient({ baseUrl, shopId: 'shop-1', formId: 'form-1', accessToken: form.accessToken });
  assert.equal((await guest.get()).customer.name, '홍길동');
  const submit = newCommand('intake.submit', 0, { id: 'form-1', people: [person()], status: 'submitted' });
  const response = await guest.submit(submit); assert.equal(response.submissionVersion, 1); assert.equal((await guest.submit(submit)).duplicate, true);
  assert.equal((await store.intake('form-1')).submittedPeople, 1);
  assert.equal((await guest.get()).reviews, undefined); assert.equal((await driver.snapshot()).forms, undefined);
  const forged = { ...submit, requestId: 'forge', expectedVersion: 1, payload: { ...submit.payload, reviewed: true } };
  await assert.rejects(guest.submit(forged), errorCode('INVALID_INPUT'));
  const unauthenticated = await fetch(baseUrl + '/api/workflows'); assert.equal(unauthenticated.status, 401);
  const wrongToken = createGuestHttpClient({ baseUrl, shopId: 'shop-1', formId: 'form-1', accessToken: 'x'.repeat(48) });
  await assert.rejects(wrongToken.get(), errorCode('UNAUTHORIZED'));
  const nullSubmit = await fetch(baseUrl + '/api/intake/shop-1/form-1', { method: 'POST', headers: { Authorization: 'Form ' + form.accessToken, 'Content-Type': 'application/json' }, body: 'null' });
  assert.equal(nullSubmit.status, 400);
  await store.execute(newCommand('intake.review', await store.snapshot(), { id: 'form-1', submissionVersion: 1 }));
  await store.execute(newCommand('print.request', await store.snapshot(), { id: 'a4', kind: 'a4', formIds: ['form-1'] }));
  assert.ok((await store.print('a4')).html.includes('장비 준비표'));
  assert.equal((await store.dispatchPrint('a4')).transportConfigured, false);
  await assert.rejects(driver.print('a4'), errorCode('FORBIDDEN'));
  await store.execute(newCommand('intake.revoke', await store.snapshot(), { id: 'form-1' }));
  await assert.rejects(guest.get(), errorCode('FORM_CLOSED'));
});

test('HTTP client preserves uncertain writes for explicit same-command retry and rejects insecure endpoints', async () => {
  const sent = [], command = newCommand('stock.receive', 0, { sku: 'ski', quantity: 1 });
  const client = createHttpClient({ baseUrl: 'https://example.test', token: 't'.repeat(40), fetchImpl: async (url, options) => { sent.push(JSON.parse(options.body)); throw new Error('offline'); } });
  await assert.rejects(client.execute(command), errorCode('CONNECTION_ERROR'));
  assert.equal(sent.length, 1); assert.deepEqual(sent[0], command);
  assert.throws(() => createHttpClient({ baseUrl: 'http://example.test', token: 't'.repeat(40) }), errorCode('INVALID_INPUT'));
  const badResponse = createHttpClient({ baseUrl: 'https://example.test', token: 't'.repeat(40), fetchImpl: async () => ({ ok: true, json: async () => { throw new Error('bad json'); } }) });
  await assert.rejects(badResponse.snapshot(), errorCode('INVALID_RESPONSE'));
});
