const { test } = require('node:test');
const assert = require('node:assert/strict');
const { fixture, shop, van, errorCode } = require('./workflows-fixtures.cjs');
const C = require('../src/workflows/client.js');
const E = require('../src/workflows/exchanges.js');
const Demo = require('../src/workflows/demo.js');
const Returns = require('../src/returns/service.js');
const visit = { method: 'vehicle', date: '2026-09-09', time: '13:00', place: '만선 광장', vehicleId: 'van-1' };
const returnPlan = { ...visit, time: '16:30' };
function setup(quantity = 2, repository) {
  const f = fixture(repository), customer = { kind: 'customer', id: 'rental' };
  const old = f.call('stock.receive', { sku: 'ski', quantity }).assetIds;
  f.move('deliver', old, shop, customer); f.task('regular', 'collection', 'rental', old, '16:30');
  const newIds = f.call('stock.receive', { sku: 'ski', quantity: 3 }).assetIds;
  const request = (extra = {}) => f.call('exchange.request', { id: 'exchange-1', orderId: 'rental', customerId: 'rental', customerName: '김영희', kind: 'ski', baseAssetIds: old.slice(0, 1), reason: 'damage', oldSize: '150', newSize: '150', memo: '상판 파손', method: 'vehicle', visit, returnPlan, ...extra });
  return { ...f, old, newIds, request, customer, state: () => f.store.snapshot(), x: () => f.store.snapshot().exchanges[0] };
}
test('vehicle exchange separately delivers replacement, collects old equipment and receives damage in shop', () => {
  const f = setup(), before = f.state().assets.length; f.request();
  assert.equal(f.state().assets.length, before); assert.equal(f.x().units.length, 1);
  assert.deepEqual(f.state().tasks.find(t => t.id === 'regular').assetIds, f.old.slice(1));
  assert.match(f.state().tasks.find(t => t.id === 'exchange-1-new').memo, /장비교환.*스키 1대.*150 → 150/);
  assert.ok(f.driver.snapshot().notifications.records.some(n => n.taskId === 'exchange-1-new'));
  f.call('exchange.prepare', { id: 'exchange-1', assetIds: f.newIds.slice(0, 1) });
  f.move('load', f.newIds.slice(0, 1), shop, van);
  f.move('deliver', f.newIds.slice(0, 1), van, f.customer, { taskId: 'exchange-1-new' }, f.driver);
  assert.equal(f.x().units[0].collectedAt, undefined);
  assert.equal(f.state().tasks.find(t => t.id === 'exchange-1-old').status, 'waiting');
  assert.deepEqual(f.state().tasks.find(t => t.id === 'exchange-1-return-0').assetIds, f.newIds.slice(0, 1));
  assert.equal(f.state().tasks.find(t => t.id === 'exchange-1-return-0').time, '16:30');
  f.move('collect', f.old.slice(0, 1), f.customer, van, { taskId: 'exchange-1-old' }, f.driver);
  assert.equal(f.x().status, 'open'); assert.equal(f.x().units[0].receivedAt, undefined);
  f.move('receive', f.old.slice(0, 1), van, shop); assert.equal(f.x().status, 'completed');
  assert.equal(f.state().assets.find(a => a.id === f.old[0]).condition, 'damaged');
  assert.throws(() => f.move('load', f.old.slice(0, 1), shop, van), /파손품/);
  f.move('collect', f.newIds.slice(0, 1), f.customer, van, { taskId: 'exchange-1-return-0' });
  f.move('receive', f.newIds.slice(0, 1), van, shop);
  assert.equal(f.state().assets.find(a => a.id === f.old[1]).location.kind, 'customer');
});
test('unprepared, duplicate, wrong driver, stale and unrelated inventory cannot satisfy an exchange', () => {
  const f = setup(); f.request();
  const empty = f.state();
  assert.throws(() => f.call('task.allocate', { id: 'exchange-1-new', items: [{ itemId: 'ski', assetIds: f.newIds.slice(0, 1) }] }), /장비교환/);
  assert.throws(() => f.call('task.status', { id: 'exchange-1-new', status: 'completed' }), errorCode('QUANTITY_EXCEEDED'));
  assert.throws(() => f.request({ id: 'exchange-2' }), /대여 중|교환/);
  const cmd = C.newCommand('exchange.prepare', f.state(), { id: 'exchange-1', assetIds: f.newIds.slice(0, 1) });
  f.call('stock.receive', { sku: 'helmet', quantity: 1 }); assert.throws(() => f.store.execute(cmd), errorCode('VERSION_CONFLICT'));
  assert.throws(() => f.call('exchange.prepare', { id: 'exchange-1', assetIds: f.newIds.slice(0, 1) }, f.driver), errorCode('FORBIDDEN'));
  f.call('exchange.prepare', { id: 'exchange-1', assetIds: f.newIds.slice(0, 1) });
  assert.throws(() => f.move('deliver', f.newIds.slice(0, 1), shop, f.customer), /연결된/);
  assert.throws(() => f.move('load', f.newIds.slice(0, 1), shop, { kind: 'vehicle', id: 'van-2' }), /담당 차량/);
  assert.throws(() => f.move('directReturn', f.old.slice(0, 1), f.customer, shop), /연결된/);
  assert.throws(() => f.call('task.status', { id: 'exchange-1-old', status: 'cancelled' }), /장비교환/);
  assert.equal(empty.assets.length + 1, f.state().assets.length);
});
test('partial exchange of two boots records pairs, waits for real inventory and never returns the ski bodies', () => {
  const f = setup();
  assert.throws(() => f.request({ kind: 'ski-boots', baseAssetIds: f.old, oldSize: '255', newSize: '260' }), /기존 구성품/);
  f.request({ kind: 'ski-boots', baseAssetIds: f.old, oldSize: '255', newSize: '260', reason: 'size', confirmExistingComponent: true });
  const oldParts = f.x().units.map(u => u.oldAssetId);
  assert.equal(new Set(oldParts).size, 2); assert.equal(f.state().assets.filter(a => a.sku === 'ski-boots' && a.location.kind === 'shop').length, 0);
  assert.deepEqual(f.state().tasks.find(t => t.id === 'regular').assetIds, f.old);
  const parts = f.call('stock.receive', { sku: 'ski-boots', quantity: 2, size: '260', sourceReference: 'verified-boots-1' }).assetIds;
  assert.throws(() => f.call('stock.receive', { sku: 'ski-boots', quantity: 2, sourceReference: 'verified-boots-1' }), errorCode('ALREADY_EXISTS'));
  f.call('exchange.prepare', { id: 'exchange-1', assetIds: parts.slice(0, 1) }); f.move('load', parts.slice(0, 1), shop, van);
  f.move('deliver', parts.slice(0, 1), van, f.customer, { taskId: 'exchange-1-new' });
  assert.equal(f.x().units.filter(u => u.deliveredAt).length, 1);
  assert.throws(() => f.call('task.status', { id: 'exchange-1-new', status: 'completed' }), errorCode('QUANTITY_EXCEEDED'));
  f.move('collect', oldParts.slice(0, 1), f.customer, van, { taskId: 'exchange-1-old' });
  assert.ok(f.old.every(id => f.state().assets.find(a => a.id === id).location.kind === 'customer'));
  assert.equal(f.state().tasks.find(t => t.id === 'exchange-1-return-0').assetIds[0], parts[0]);
});
test('shop exchange and cancellation preserve original return plans; movements cannot be undone independently', () => {
  const f = setup(); f.request({ method: 'shop' });
  assert.equal(f.state().tasks.filter(t => t.exchangeId).length, 0);
  f.call('exchange.prepare', { id: 'exchange-1', assetIds: f.newIds.slice(0, 1) });
  const m = f.move('directReturn', f.old.slice(0, 1), f.customer, shop, { exchangeId: 'exchange-1' });
  assert.equal(f.x().status, 'open');
  assert.throws(() => f.call('movement.undo', { movementId: m.movementId, reason: '실수' }), errorCode('DEPENDENT_MOVEMENT'));
  f.move('deliver', f.newIds.slice(0, 1), shop, f.customer, { exchangeId: 'exchange-1' }); assert.equal(f.x().status, 'completed');
  const g = setup(); g.request(); g.call('exchange.cancel', { id: 'exchange-1', reason: '고객 요청 철회' });
  assert.equal(g.x().status, 'cancelled'); assert.equal(g.state().assets.find(a => a.id === g.old[0]).exchangeReservationId, null);
  assert.deepEqual(g.state().tasks.find(t => t.id.endsWith('restored')).assetIds, g.old.slice(0, 1));
});
test('rental projection preserves two sets, tracks component separately, and keeps prices through early old pickup', () => {
  const repo = Returns.createMemoryRepository(), f = Demo.create(repo, '2026-09-09');
  const order = { id: 'rental', customer: { name: '김영희', phone: '010-1111-2222' }, vehicleId: f.vehicleId, rental: { amountWon: 100000, paidWon: 100000 }, items: [{ id: 'ski', label: '스키', category: 'equipment', unit: '세트', plannedQuantity: 2, customerQuantity: 2, vehicleQuantity: 0, shopQuantity: 0, returnPlan: { method: 'direct', date: '2026-09-09', time: '16:30', place: '만선 광장' } }] };
  f.importOrder(order, true); const old = f.projectOrder('rental').bindings[0].assetIds;
  const request = { id: 'exchange-1', orderId: 'rental', customerId: 'rental', customerName: '김영희', kind: 'ski', baseAssetIds: old.slice(0, 1), reason: 'damage', oldSize: '150', newSize: '150', memo: '', method: 'vehicle', visit: { ...visit, vehicleId: f.vehicleId }, returnPlan: { ...returnPlan, vehicleId: f.vehicleId } };
  f.run('exchange.request', request);
  f.run('stock.move', { kind: 'collect', assetIds: old.slice(0, 1), from: { kind: 'customer', id: 'rental' }, to: f.van, taskId: 'exchange-1-old' });
  assert.equal(f.projectOrder('rental').items[0].shopQuantity, 0); assert.equal(f.projectOrder('rental').items[0].vehicleQuantity, 0); assert.equal(f.projectOrder('rental').items[0].exchangePendingQuantity, 1);
  const fresh = f.run('stock.receive', { sku: 'ski', quantity: 1 }).assetIds;
  f.run('exchange.prepare', { id: 'exchange-1', assetIds: fresh }); f.loadDelivery('exchange-1-new');
  f.run('stock.move', { kind: 'deliver', assetIds: fresh, from: f.van, to: { kind: 'customer', id: 'rental' }, taskId: 'exchange-1-new' });
  const after = f.projectOrder('rental'); assert.equal(after.items[0].returnTarget, 2); assert.equal(after.items[0].customerQuantity, 2); assert.equal(after.items[0].exchangePendingQuantity, 0); assert.equal(after.rental.amountWon, 100000);
  assert.deepEqual(after.bindings[0].assetIds, [fresh[0], old[1]]);
  f.run('stock.move', { kind: 'receive', assetIds: old.slice(0, 1), from: f.van, to: f.shop });
  f.run('exchange.request', { ...request, id: 'boots', kind: 'ski-boots', baseAssetIds: fresh, oldSize: '255', newSize: '260', reason: 'size', method: 'shop', confirmExistingComponent: true });
  const boot = f.run('stock.receive', { sku: 'ski-boots', quantity: 1, size: '260' }).assetIds;
  f.run('exchange.prepare', { id: 'boots', assetIds: boot });
  f.run('stock.move', { kind: 'deliver', assetIds: boot, from: f.shop, to: { kind: 'customer', id: 'rental' }, exchangeId: 'boots' });
  let projected = f.projectOrder('rental'); assert.equal(projected.items.find(i => i.component).customerQuantity, 1); assert.equal(projected.items[0].plannedQuantity, 2);
  f.returnCustomer('rental', [...fresh, old[1], ...boot]);
  assert.equal(f.projectOrder('rental').status, 'awaiting_exchange', 'old boots remain outstanding even after current rental items return');
  const oldBoot = f.snap().exchanges.find(x => x.id === 'boots').units[0].oldAssetId;
  f.run('stock.move', { kind: 'directReturn', assetIds: [oldBoot], from: { kind: 'customer', id: 'rental' }, to: f.shop, exchangeId: 'boots' });
  assert.equal(f.projectOrder('rental').status, 'returned');

});

test('SQLite persists linked exchange tasks and duplicate request creates no additional components', t => {
  const { createSqliteRepository } = require('../server/returns-repository.cjs');
  const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'skinote-exchange-')), file = path.join(dir, 'test.sqlite');
  let repository = createSqliteRepository(file); t.after(() => { repository.close(); fs.rmSync(dir, { recursive: true }); });
  const f = setup(2, repository); f.request({ kind: 'poles', oldSize: '110', newSize: '110', confirmExistingComponent: true });
  const stock = f.call('stock.receive', { sku: 'poles', quantity: 1 }).assetIds;
  const command = C.newCommand('exchange.prepare', f.state(), { id: 'exchange-1', assetIds: stock });
  f.store.execute(command); const before = f.state(); assert.equal(f.store.execute(command).duplicate, true);
  repository.close(); repository = createSqliteRepository(file);
  const next = fixture(repository).store.snapshot(); assert.deepEqual(next.exchanges, before.exchanges); assert.deepEqual(next.assets, before.assets); assert.deepEqual(next.tasks, before.tasks);
});
test('healthy exchanged equipment can be reused by another rental without rewriting its identity', () => {
  const f = setup(); f.request({ method: 'shop', reason: 'size', newSize: '155' });
  f.call('exchange.prepare', { id: 'exchange-1', assetIds: f.newIds.slice(0, 1) });
  f.move('deliver', f.newIds.slice(0, 1), shop, f.customer, { exchangeId: 'exchange-1' });
  f.move('directReturn', f.old.slice(0, 1), f.customer, shop, { exchangeId: 'exchange-1' });
  f.move('deliver', f.old.slice(0, 1), shop, { kind: 'customer', id: 'next-rental' });
  assert.equal(E.resolve(f.repository.workflows('shop-1'), f.old[0], 'rental'), f.newIds[0]);
  assert.equal(E.resolve(f.repository.workflows('shop-1'), f.old[0], 'next-rental'), f.old[0]);
});
test('new intake customer projection adds a single exchanged component without duplicate delivery counts', async () => {
  const repository = Returns.createMemoryRepository(), f = Demo.create(repository, '2026-09-09');
  const id = await f.createForm({ customer: { name: '새 고객', phone: '010-1111-2222' }, expectedPeople: 1 });
  const person = { id: 'person-1', name: '새 고객', equipment: 'ski', heightCm: 170, footMm: 255, clothing: false, clothingSize: '', helmet: false };
  f.run('intake.submit', { id, people: [person], status: 'submitted' }); f.run('intake.review', { id, submissionVersion: 1 }); f.run('intake.prepare', { id, reviewVersion: 1, personIds: [person.id] });
  const ski = f.run('stock.receive', { sku: 'ski', quantity: 1 }).assetIds;
  f.run('intake.issue', { id, reviewVersion: 1, from: f.shop, people: [{ personId: person.id, assetIds: ski, actualFootMm: 255, actualEquipmentSize: '150' }] });
  f.run('exchange.request', { id: 'boots', orderId: id, customerId: id, customerName: person.name, kind: 'ski-boots', baseAssetIds: ski, reason: 'size', oldSize: '255', newSize: '260', memo: '', method: 'shop', visit: { ...visit, vehicleId: f.vehicleId }, returnPlan: { ...returnPlan, method: 'direct', vehicleId: f.vehicleId }, confirmExistingComponent: true });
  const boots = f.run('stock.receive', { sku: 'ski-boots', quantity: 1, size: '260' }).assetIds; f.run('exchange.prepare', { id: 'boots', assetIds: boots });
  f.run('stock.move', { kind: 'deliver', assetIds: boots, from: f.shop, to: { kind: 'customer', id }, exchangeId: 'boots' });
  const projected = f.projectOrder(id); assert.equal(projected.items.filter(i => i.component).length, 1); assert.equal(projected.items.find(i => i.component).customerQuantity, 1); assert.equal(projected.items.find(i => i.id === 'ski').customerQuantity, 1);
});
